#!/usr/bin/env bash

name=$(gh cs ls --json name --jq '.[0].name');
port=1080;

trap '
  gh cs stop -c $name;
' EXIT;

# am start -n com.github.metacubex.clash.meta/com.github.kr328.clash.MainActivity;

echo "Waiting...";

gh cs ssh -c $name -- -L $port:localhost:$port "microsocks -p $port";

curl -sL https://raw.githubusercontent.com/Timeree/Timeree/main/vpn/bindSocks5 | bash