#!/usr/bin/env bash

CODESPACE_NAME=$(gh cs ls --json name --jq '.[0].name')

SOCKS5_PORT=10351

FTP_PORT=2121
FTP_PORTR1=52121
FTP_PORTR2=52122

echo $CODESPACE_NAME

gh cs ssh -c $CODESPACE_NAME -- \
  -L $SOCKS5_PORT:localhost:$SOCKS5_PORT \
  -L $FTP_PORT:localhost:$FTP_PORT \
  -L $FTP_PORTR1:localhost:$FTP_PORTR1 \
  -L $FTP_PORTR2:localhost:$FTP_PORTR2 \
  "
    microsocks -p $SOCKS5_PORT &
    python3 -m pyftpdlib -p $FTP_PORT -r $FTP_PORTR1-$FTP_PORTR2 -w -d ~ &
    sudo nginx -c ~/nginx.conf &
    tail -f /dev/null
  "

# curl -sL https://raw.githubusercontent.com/Timeree/Timeree/main/server/bind | bash;

