#!/usr/bin/env bash

CODESPACE_NAME=$(gh cs ls --json name --jq '.[0].name')

echo $CODESPACE_NAME

gh cs ssh -c $CODESPACE_NAME -- \
  "
    (
      sleep 5
      echo \"/l $MCC_PASSWORD\" &
      sleep 2
      echo \"/home\" &
    ) | ~/mccx86 $MCC_USERNAME - $MCC_SERVER &
    sleep 10
  "

gh cs ssh -c $CODESPACE_NAME -- \
  "
    (
      sleep 5
      echo \"/l $MCC_PASSWORD\" &
      sleep 2
      echo \"/home\" &
    ) | ~/mccx86 $MCC_USERNAME2 - $MCC_SERVER &
  "


