#!/usr/bin/env bash

CODESPACE_NAME=$(gh cs ls --json name --jq '.[0].name')

trap '
  gh cs stop -c $CODESPACE_NAME
' EXIT;

echo $CODESPACE_NAME

while true
    sleep 180
    echo "# running..."
end | gh cs ssh -- "
    (
        sleep 5
        echo \"/l \$MCC_PASSWORD\" &
    ) | ~/mccx86 \$MCC_USERNAME - \$MCC_SERVER &
    sleep 10

    (
        sleep 5
        echo \"/l \$MCC_PASSWORD\" &
    ) | ~/mccx86 \$MCC_USERNAME2 - \$MCC_SERVER &
    sleep 10
"