#!/usr/bin/env bash

sudo apt update;
sudo apt install microsocks -y;

pip install pyftpdlib



# curl -fsSL https://raw.githubusercontent.com/Timeree/Timeree/main/tools/initghcs | bash

# curl -fsSL https://ollama.com/install.sh | sh

