#!/usr/bin/env bash

(
  set -eux

  cd . || exit

  CODESPACE_NAME=$(gh cs ls --json name --jq '.[0].name')

  gh cs delete -c $CODESPACE_NAME

  gh cs create --repo Timeree/Timeree

  CODESPACE_NAME=$(gh cs ls --json name --jq '.[0].name')

  echo $CODESPACE_NAME

)