#!/usr/bin/env bash

chmod +x ~/Timeree/tools/*

(
  cd ~/Timeree || exit

  git add .

  msg=$(date +%s | sha256sum | head -c 8)
  git commit -m "$msg" 2>/dev/null

  if [ "$1" = "push" ]; then
    git push --force
  fi

  git gc --prune=now
)
