#!/usr/bin/env bash

chmod +x ~/Timeree/tools/*

(
  cd ~/Timeree || exit

  git add .

  msg=$(date +%s | sha256sum | head -c 8)

  git commit -m "$msg"
  
  if [ "$1" = "push" ]; then
  
    git push --force
    
    exit 0
    
  fi
)
