#!/usr/bin/env bash

am start -n com.github.metacubex.clash.meta/com.github.kr328.clash.MainActivity

trap '
  am start -n com.github.metacubex.clash.meta/com.github.kr328.clash.MainActivity
' EXIT;

bash ~/Timeree/tools/bindServer
