#!/usr/bin/env bash

CODESPACE_NAME=$(gh cs ls --json name --jq '.[0].name')

SOCKS5_PORT=10351

trap '
  gh cs stop -c $CODESPACE_NAME
  echo "Exit"
' EXIT;

echo $CODESPACE_NAME

gh cs ssh -c $CODESPACE_NAME -- \
  -L $SOCKS5_PORT:localhost:$SOCKS5_PORT \
  "
    microsocks -p $SOCKS5_PORT &
    tail -f /dev/null
  "

# curl -sL https://raw.githubusercontent.com/Timeree/Timeree/main/tools/vpn | bash;

